language: ruby

services:
  - postgresql

script:
  - bundle exec rspec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: "9.6"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn

cache:
  yarn: true

bundler_args: --without production development
